#! /bin/sh

PATTERN='\s*baseurl=.+'
COMMAND=$1
DESC=$2
URL=""
CFG_PATH="/etc/yum.repos.d"

case ${COMMAND} in
    "switch")
        case $DESC in
            "sustech")
                URL="https://mirrors.sustech.edu.cn"
                ;;
            "hitsz")
                URL="http://10.249.12.85"
                ;;
            "bfsu")
                URL="https://mirrors.bfsu.edu.cn"
                ;;
            *)
                printf "No mirror selected.\n"
                exit 1
                ;;
        esac
        ;;
    "set")
        URL=${DESC}
        ;;
    *)
        printf "DNF Mirror Utility\n\nCOMMAND:\n\tswitch <mirror name>\n\tset <mirror URL>\n"
        exit 0
        ;;
esac

if [ ${EUID} != 0 ]; then
    sudo "$0" "$@"
    exit $?
fi

sed -E -i 's,'${PATTERN}',baseurl='${URL}'/fedora/releases/$releasever/Everything/$basearch/os/,g' ${CFG_PATH}/fedora.repo
sed -E -i 's,'${PATTERN}',baseurl='${URL}'/fedora/updates/$releasever/Everything/$basearch/,g' ${CFG_PATH}/fedora-updates.repo
sed -E -i 's,'${PATTERN}',baseurl='${URL}'/fedora/releases/$releasever/Modular/$basearch/os/,g' ${CFG_PATH}/fedora-modular.repo
sed -E -i 's,'${PATTERN}',baseurl='${URL}'/fedora/updates/$releasever/Modular/$basearch/,g' ${CFG_PATH}/fedora-updates-modular.repo
dnf makecache
